import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Inter'],
                'display-lg': ['Inter'],
                'body-md': ['Inter'],
                'title-md': ['Inter'],
                'headline-lg': ['Inter'],
                'label-sm': ['Inter'],
                'label-md': ['Inter'],
                'headline-lg-mobile': ['Inter'],
            },
            fontSize: {
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
            },
            colors: {
                'secondary-container': '#86f2e4',
                'surface-variant': '#d5e3fc',
                'surface-container-low': '#eff4ff',
                'secondary-fixed': '#89f5e7',
                'primary-fixed-dim': '#b8c4ff',
                'on-primary-fixed': '#001453',
                'surface-dim': '#ccdbf3',
                'surface-bright': '#f8f9ff',
                'inverse-primary': '#b8c4ff',
                'surface-container-high': '#dce9ff',
                'tertiary-fixed': '#e0e3e5',
                'surface-container-highest': '#d5e3fc',
                'on-background': '#0d1c2e',
                'on-secondary-fixed': '#00201d',
                'on-error-container': '#93000a',
                'on-surface-variant': '#444653',
                'secondary-fixed-dim': '#6bd8cb',
                'primary-container': '#1e40af',
                'primary-fixed': '#dde1ff',
                'on-primary-container': '#a8b8ff',
                'surface-tint': '#3755c3',
                'surface-container': '#e6eeff',
                outline: '#757684',
                'on-secondary': '#ffffff',
                'tertiary-container': '#484c4e',
                tertiary: '#323537',
                'on-primary': '#ffffff',
                'on-secondary-fixed-variant': '#005049',
                'on-tertiary-fixed-variant': '#444749',
                'outline-variant': '#c4c5d5',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                'on-surface': '#0d1c2e',
                'on-tertiary': '#ffffff',
                secondary: '#006a61',
                'on-secondary-container': '#006f66',
                'on-tertiary-fixed': '#191c1e',
                'on-primary-fixed-variant': '#173bab',
                primary: '#00288e',
                'inverse-on-surface': '#eaf1ff',
                'tertiary-fixed-dim': '#c4c7c9',
                background: '#f8f9ff',
                error: '#ba1a1a',
                'inverse-surface': '#233144',
                surface: '#f8f9ff',
                'surface-container-lowest': '#ffffff',
                'on-tertiary-container': '#b9bcbe',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                lg: '24px',
                gutter: '24px',
                base: '4px',
                xl: '40px',
                md: '16px',
                'container-max': '1280px',
                sm: '8px',
                xs: '4px',
            },
        },
    },

    plugins: [forms],
};
