import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Inter'],
                'display-lg': ['Inter'],
                'body-md': ['Inter'],
                'title-md': ['Inter'],
                'headline-lg': ['Inter'],
                'label-sm': ['Inter'],
                'label-md': ['Inter'],
                'headline-lg-mobile': ['Inter'],
            },
            fontSize: {
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
            },
            colors: {
                'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
                'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
                'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
                'secondary-fixed': 'rgb(var(--color-secondary-fixed) / <alpha-value>)',
                'primary-fixed-dim': 'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
                'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
                'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
                'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
                'inverse-primary': 'rgb(var(--color-inverse-primary) / <alpha-value>)',
                'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
                'tertiary-fixed': 'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
                'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
                'on-background': 'rgb(var(--color-on-background) / <alpha-value>)',
                'on-secondary-fixed': 'rgb(var(--color-on-secondary-fixed) / <alpha-value>)',
                'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
                'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
                'secondary-fixed-dim': 'rgb(var(--color-secondary-fixed-dim) / <alpha-value>)',
                'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
                'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value>)',
                'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
                'surface-tint': 'rgb(var(--color-surface-tint) / <alpha-value>)',
                'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
                outline: 'rgb(var(--color-outline) / <alpha-value>)',
                'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
                'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
                tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
                'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
                'on-secondary-fixed-variant': 'rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)',
                'on-tertiary-fixed-variant': 'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',
                'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
                'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
                'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
                'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
                'on-tertiary': 'rgb(var(--color-on-tertiary) / <alpha-value>)',
                secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
                'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
                'on-tertiary-fixed': 'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
                'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
                primary: 'rgb(var(--color-primary) / <alpha-value>)',
                'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
                'tertiary-fixed-dim': 'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
                background: 'rgb(var(--color-background) / <alpha-value>)',
                error: 'rgb(var(--color-error) / <alpha-value>)',
                'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
                surface: 'rgb(var(--color-surface) / <alpha-value>)',
                'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
                'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                lg: '24px',
                gutter: '24px',
                base: '4px',
                xl: '40px',
                md: '16px',
                'container-max': '1280px',
                sm: '8px',
                xs: '4px',
            },
        },
    },

    plugins: [forms],
};
